CREATE TABLE connection
(
    user_id      BIGINT NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255),
    status       BOOLEAN,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    bio          VARCHAR(255),
    birthdate    date,
    phone_number VARCHAR(255),
    language     VARCHAR(255),
    is_private   BOOLEAN,
    CONSTRAINT pk_connection PRIMARY KEY (user_id)
);

CREATE TABLE content
(
    user_id      BIGINT NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255),
    status       BOOLEAN,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    bio          VARCHAR(255),
    birthdate    date,
    phone_number VARCHAR(255),
    language     VARCHAR(255),
    is_private   BOOLEAN,
    CONSTRAINT pk_content PRIMARY KEY (user_id)
);

CREATE TABLE cr
(
    user_id      BIGINT NOT NULL,
    username     VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255),
    status       BOOLEAN,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    bio          VARCHAR(255),
    birthdate    date,
    phone_number VARCHAR(255),
    language     VARCHAR(255),
    is_private   BOOLEAN,
    CONSTRAINT pk_cr PRIMARY KEY (user_id)
);

CREATE TABLE message
(
    message_id  BIGINT NOT NULL,
    sender_id   BIGINT,
    receiver_id BIGINT,
    content     VARCHAR(255),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    is_read     BOOLEAN,
    CONSTRAINT pk_message PRIMARY KEY (message_id)
);

CREATE TABLE notifications
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255),
    message   VARCHAR(255),
    date_time TIMESTAMP WITHOUT TIME ZONE,
    is_read   BOOLEAN,
    user_id   BIGINT,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255),
    password        VARCHAR(255),
    email           VARCHAR(255),
    status          BOOLEAN,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    bio             VARCHAR(255),
    birthdate       date,
    phone_number    VARCHAR(255),
    language        VARCHAR(255),
    is_private      BOOLEAN,
    profile_picture VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_phonenumber UNIQUE (phone_number);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);